name: news_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.9.0
  card_slider: ^1.0.5
  flutter_custom_caraousel_v2: ^0.2.0
  widget_slider: ^0.1.0
  cached_network_image: ^3.4.1
  path_provider: ^2.1.5
  google_fonts: ^6.3.1
  url_launcher: ^6.2.5
  webview_flutter: ^4.13.0
  flutter_native_splash: ^2.4.6
  flutter_launcher_icons: ^0.14.4
  icons_plus: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_native_splash:
  image: assets/images/blackLogo.png
  color: "#00000f"
  android: true
  ios: true
  android_gravity: center
  

flutter_icons:
  android: true
  ios: true
  image_path: assets/images/blackLogo.png
